### ISSUE TITLE
currency does not appear to populate when token is dropped

### ISSUE THREAD

**Issue by SR5060** [DFreds/dfreds-pocket-change#14]
I've tested with confirming NPC type and and zero percent change of no currency. Error message:

TypeError: Cannot read property 'toLowerCase' of undefined
    at Validator._isMatchingType (modules/dfreds-pocket-change/scripts/validator.js:84)

**Comment by DFreds** [comment]
Thanks for the stack trace. What is the creature type of the NPC you're dropping in set to? Examples: plant, giant, monstrosity, fiend, humanoid

**Comment by SR5060** [comment]
tried on two different humanoids

**Comment by SR5060** [comment]
yea, It doesn't appear that the error is thrown for other types

**Comment by DFreds** [comment]
I feel like there might be some kind of migration error here or something. When you open the character sheet for that actor and hit the gear icon where Type goes, does it say it is a humanoid? Because otherwise I'm not having any issues.

I'll still add some safety checks so that doesn't happen though, so expect those in the near future.

**Comment by SR5060** [comment]
bummer, yea looks like you are right. when I "reupdate" the type and then test again, it doesn't throw the error, so something must be messed up in my actor db.

**Comment by SR5060** [comment]
thanks for helping troubleshoot

**Comment by DFreds** [comment]
No problem. Migration issues are weird. I'll have an update out today to stop the error from being thrown

**Comment by DFreds** [comment]
Fixed in 2.0.3
