### ISSUE TITLE
Convert Selected Tokens to Loot almost works...

### ISSUE THREAD

**Issue by MyklKelsey** [DFreds/dfreds-pocket-change#29]
Hey, this is great - but I'm having some bug going on...

When I run the macro then open the token -
1) It shows the LootSheet5eNPC << so that's good
2) But the currencies are [object Object], [object Object], [object Object], [object Object], and the last one is [object Object].

How can I tell which is which? Also in the lower left for the Coin distribution, the same problem down there.

Maybe it's something with my setup?

Looking forward to the fix, thanks again!

**Comment by DFreds** [comment]
To be clear, you guys are seeing this.

![image](https://user-images.githubusercontent.com/11878569/137591883-d4dfd7a8-5be8-4ac2-a961-eaed4cd33c4a.png)

This is not an issue with Pocket Change. It is an issue with LootSheet... maybe caused by 1.5.2 version of dnd5e. Is that the version you're on?

This occurs changing any NPC to a loot sheet, even when Pocket Change is not enabled. You should make an issue [here](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues) and hope it gets some traction to be resolved.

**Comment by DFreds** [comment]
Oh, actually it looks like LootSheet updated yesterday, causing a new type of problem with rendering it. I'll fix that
